project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
    - "!publications/pub-list.ejs.md"
    - "!publications/pub-list-home.ejs.md"

website:
  title: "Andrea Ruglioni"
  google-analytics:
    tracking-id: "G-5C5F2JCMQ1"
  cookie-consent: true
  site-url: https://ruglio.github.io/WEB_andrearuglioni/
  description: "Doctoral candidate in quantitative finance at Swiss Finance Institute, EPFL"
  favicon: assets/images/logo.svg
  page-navigation: true
  back-to-top-navigation: false
  search: false

  navbar:
    logo: assets/images/logo.svg
    # tools:
    #   - icon: github
    #     href: https://github.com/Ruglio
    #   - icon: linkedin
    #     href: https://www.linkedin.com/in/andrea-ruglioni
    #   - icon: envelope
    #     aria-label: email
    #     href: mailto:ruglioni07@gmail.com
    right:
      - text: Blog
        aria-label: "Blog"
        href: blog/index.html
      - text: Teaching
        aria-label: "Teaching"
        href: teaching/index.html
      - text: Publications
        aria-label: "Publications"
        href: publications/index.html

  page-footer:
    left: >-
     &#169; 2024-2026 Andrea Ruglioni
    center: |
      <a class="footer-link" href="https://github.com/Ruglio" title="github">{{< fa brands github >}}</a>
      <a class="footer-link" href="https://linkedin.com/in/andrea-ruglioni" title="LinkedIn">{{< fa brands linkedin >}}</a>
      <a class="footer-link" href="https://orcid.org/0009-0003-5208-5907" title="orcid">{{< ai orcid >}}</a>
      <a class="footer-link" href="https://scholar.google.com/citations?user=3sdazUQAAAAJ&hl=en" title="Google Scholar">{{< ai google-scholar >}}</a>
      <a class="footer-link" href=mailto:andrea.ruglioni@epfl.ch title="envelope">{{< fa envelope >}}</a>
      <a class="footer-link" href="blog/index.xml" title="RSS Feed">{{< fa rss >}}</a>
    right: 
      Made with [Quarto](https://quarto.org)<br>
      [Source code on {{< fa brands github >}} GitHub](https://github.com/Ruglio/WEB_andrearuglioni)


format:
  html:
    theme:
      light: [flatly, assets/styles/theme_light.scss]
      dark: [darkly, assets/styles/theme_dark.scss]
    css: assets/styles/styles.css
    code-link: true
    lightbox: true
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,400;0,500;0,600;1,400;1,500&display=swap" rel="stylesheet">


page-layout: full


execute: 
  freeze: auto